-- Retention domain (REVIEW_SERVICE) — cards, schedule, attempts, daily queue
USE [REVIEW_SERVICE]
GO

IF OBJECT_ID('dbo.RETENTION_CARD', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.RETENTION_CARD (
        CARDID              BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USERID              INT NOT NULL,
        SOURCETYPE          NVARCHAR(32) NOT NULL, -- ENROLLMENT_SLOT | GUIDED_TOPIC
        SOURCEID            NVARCHAR(64) NOT NULL,
        ENROLLMENTID        BIGINT NULL,
        PLANID              BIGINT NULL,
        SLOTID              BIGINT NULL,
        TOPICID             INT NULL,
        TITLE               NVARCHAR(300) NULL,
        SLOTTYPE            NVARCHAR(30) NULL,
        REVIEWMETHOD        NVARCHAR(32) NOT NULL CONSTRAINT DF_RC_METHOD DEFAULT (N'SPACED'),
        REVIEWDIFFICULTY    NVARCHAR(16) NULL,
        REVIEWTEMPLATE      NVARCHAR(32) NULL,
        ESTIMATEDRECALLMINUTES INT NULL,
        REVIEWCONFIGJSON    NVARCHAR(MAX) NULL,
        MASTERYSTATE        NVARCHAR(32) NOT NULL CONSTRAINT DF_RC_MASTERY DEFAULT (N'LEARNING'),
        ISACTIVE            BIT NOT NULL CONSTRAINT DF_RC_ACTIVE DEFAULT (1),
        CREATEDDATE         DATETIME2(7) NOT NULL CONSTRAINT DF_RC_CREATED DEFAULT (SYSUTCDATETIME()),
        UPDATEDDATE         DATETIME2(7) NULL,
        CONSTRAINT UQ_RC_USER_SOURCE UNIQUE (USERID, SOURCETYPE, SOURCEID)
    );
    CREATE INDEX IX_RC_USER_ACTIVE ON dbo.RETENTION_CARD (USERID, ISACTIVE);
    CREATE INDEX IX_RC_ENROLLMENT ON dbo.RETENTION_CARD (ENROLLMENTID) WHERE ENROLLMENTID IS NOT NULL;
END
GO

IF OBJECT_ID('dbo.RETENTION_SCHEDULE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.RETENTION_SCHEDULE (
        SCHEDULEID          BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        CARDID              BIGINT NOT NULL,
        DUEAT               DATE NOT NULL,
        INTERVALDAYS        INT NOT NULL CONSTRAINT DF_RS_INTERVAL DEFAULT (1),
        REPETITION          INT NOT NULL CONSTRAINT DF_RS_REP DEFAULT (0),
        EASEFACTOR          DECIMAL(6,3) NOT NULL CONSTRAINT DF_RS_EASE DEFAULT (2.500),
        STABILITY           DECIMAL(10,4) NULL,
        DIFFICULTY          DECIMAL(10,4) NULL,
        LASTREVIEWEDAT      DATETIME2(7) NULL,
        NEXTACTION          NVARCHAR(32) NULL,
        UPDATEDDATE         DATETIME2(7) NULL,
        CONSTRAINT FK_RS_CARD FOREIGN KEY (CARDID) REFERENCES dbo.RETENTION_CARD(CARDID)
    );
    CREATE UNIQUE INDEX UQ_RS_CARD ON dbo.RETENTION_SCHEDULE (CARDID);
    CREATE INDEX IX_RS_DUE ON dbo.RETENTION_SCHEDULE (DUEAT);
END
GO

IF OBJECT_ID('dbo.RETENTION_ATTEMPT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.RETENTION_ATTEMPT (
        ATTEMPTID           BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        CARDID              BIGINT NOT NULL,
        USERID              INT NOT NULL,
        OUTCOME             NVARCHAR(32) NOT NULL, -- AGAIN | HARD | GOOD | EASY | COMPLETED
        CONFIDENCE          TINYINT NULL,
        DURATIONSECONDS     INT NULL,
        TEMPLATEUSED        NVARCHAR(32) NULL,
        RESPONSEJSON        NVARCHAR(MAX) NULL,
        ATTEMPTEDAT         DATETIME2(7) NOT NULL CONSTRAINT DF_RA_AT DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT FK_RA_CARD FOREIGN KEY (CARDID) REFERENCES dbo.RETENTION_CARD(CARDID)
    );
    CREATE INDEX IX_RA_CARD ON dbo.RETENTION_ATTEMPT (CARDID, ATTEMPTEDAT DESC);
    CREATE INDEX IX_RA_USER ON dbo.RETENTION_ATTEMPT (USERID, ATTEMPTEDAT DESC);
END
GO

IF OBJECT_ID('dbo.RETENTION_DAILY_QUEUE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.RETENTION_DAILY_QUEUE (
        QUEUEID             BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USERID              INT NOT NULL,
        QUEUEDATE           DATE NOT NULL,
        CARDID              BIGINT NOT NULL,
        PRIORITY            INT NOT NULL CONSTRAINT DF_RQ_PRI DEFAULT (100),
        STATUS              NVARCHAR(20) NOT NULL CONSTRAINT DF_RQ_ST DEFAULT (N'DUE'),
        CREATEDDATE         DATETIME2(7) NOT NULL CONSTRAINT DF_RQ_CR DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT UQ_RQ_USER_DAY_CARD UNIQUE (USERID, QUEUEDATE, CARDID),
        CONSTRAINT FK_RQ_CARD FOREIGN KEY (CARDID) REFERENCES dbo.RETENTION_CARD(CARDID)
    );
    CREATE INDEX IX_RQ_USER_DAY ON dbo.RETENTION_DAILY_QUEUE (USERID, QUEUEDATE, STATUS);
END
GO

CREATE OR ALTER PROCEDURE dbo.USP_RETENTION_UPSERT_FROM_SLOT
(
    @USERID INT,
    @ENROLLMENTID BIGINT = NULL,
    @PLANID BIGINT = NULL,
    @SLOTID BIGINT,
    @TITLE NVARCHAR(300) = NULL,
    @SLOTTYPE NVARCHAR(30) = NULL,
    @REQUIRESREVIEW BIT = 0,
    @REVIEWMETHOD NVARCHAR(32) = NULL,
    @REVIEWDIFFICULTY NVARCHAR(16) = NULL,
    @REVIEWTEMPLATE NVARCHAR(32) = NULL,
    @ESTIMATEDRECALLMINUTES INT = NULL,
    @REVIEWCONFIGJSON NVARCHAR(MAX) = NULL,
    @FIRSTINTERVALDAYS INT = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    IF ISNULL(@REQUIRESREVIEW, 0) = 0
       OR UPPER(ISNULL(@REVIEWMETHOD, N'NONE')) IN (N'NONE', N'')
    BEGIN
        SELECT 1 AS SUCCESS, NULL AS CARDID, 'NO_REVIEW_REQUIRED' AS ACTION;
        RETURN;
    END

    DECLARE @SOURCEID NVARCHAR(64) = CONCAT(N'slot:', CAST(@SLOTID AS NVARCHAR(32)));
    DECLARE @METHOD NVARCHAR(32) = UPPER(@REVIEWMETHOD);
    DECLARE @CARDID BIGINT;
    DECLARE @INTERVAL INT = ISNULL(@FIRSTINTERVALDAYS,
        CASE @METHOD
            WHEN N'PERIODIC' THEN 7
            WHEN N'REFLECTION' THEN 3
            WHEN N'PRACTICE_REMINDER' THEN 2
            WHEN N'MANUAL' THEN 1
            ELSE 1
        END);

    IF @METHOD = N'MANUAL'
        SET @INTERVAL = 0; -- due immediately when user opens Manual queue; still create card

    MERGE dbo.RETENTION_CARD AS T
    USING (SELECT @USERID AS USERID, N'ENROLLMENT_SLOT' AS SOURCETYPE, @SOURCEID AS SOURCEID) AS S
    ON T.USERID = S.USERID AND T.SOURCETYPE = S.SOURCETYPE AND T.SOURCEID = S.SOURCEID
    WHEN MATCHED THEN UPDATE SET
        ENROLLMENTID = COALESCE(@ENROLLMENTID, T.ENROLLMENTID),
        PLANID = COALESCE(@PLANID, T.PLANID),
        SLOTID = @SLOTID,
        TITLE = COALESCE(@TITLE, T.TITLE),
        SLOTTYPE = COALESCE(@SLOTTYPE, T.SLOTTYPE),
        REVIEWMETHOD = @METHOD,
        REVIEWDIFFICULTY = COALESCE(@REVIEWDIFFICULTY, T.REVIEWDIFFICULTY),
        REVIEWTEMPLATE = COALESCE(@REVIEWTEMPLATE, T.REVIEWTEMPLATE),
        ESTIMATEDRECALLMINUTES = COALESCE(@ESTIMATEDRECALLMINUTES, T.ESTIMATEDRECALLMINUTES),
        REVIEWCONFIGJSON = COALESCE(@REVIEWCONFIGJSON, T.REVIEWCONFIGJSON),
        ISACTIVE = 1,
        UPDATEDDATE = SYSUTCDATETIME()
    WHEN NOT MATCHED THEN INSERT
        (USERID, SOURCETYPE, SOURCEID, ENROLLMENTID, PLANID, SLOTID, TITLE, SLOTTYPE,
         REVIEWMETHOD, REVIEWDIFFICULTY, REVIEWTEMPLATE, ESTIMATEDRECALLMINUTES, REVIEWCONFIGJSON,
         MASTERYSTATE, ISACTIVE)
        VALUES
        (@USERID, N'ENROLLMENT_SLOT', @SOURCEID, @ENROLLMENTID, @PLANID, @SLOTID, @TITLE, @SLOTTYPE,
         @METHOD, @REVIEWDIFFICULTY, @REVIEWTEMPLATE, @ESTIMATEDRECALLMINUTES, @REVIEWCONFIGJSON,
         N'LEARNING', 1);

    SELECT @CARDID = CARDID FROM dbo.RETENTION_CARD
    WHERE USERID = @USERID AND SOURCETYPE = N'ENROLLMENT_SLOT' AND SOURCEID = @SOURCEID;

    DECLARE @DUE DATE = CASE WHEN @INTERVAL <= 0 THEN CAST(SYSUTCDATETIME() AS DATE)
                             ELSE DATEADD(DAY, @INTERVAL, CAST(SYSUTCDATETIME() AS DATE)) END;

    IF NOT EXISTS (SELECT 1 FROM dbo.RETENTION_SCHEDULE WHERE CARDID = @CARDID)
        INSERT INTO dbo.RETENTION_SCHEDULE (CARDID, DUEAT, INTERVALDAYS, REPETITION)
        VALUES (@CARDID, @DUE, CASE WHEN @INTERVAL < 1 THEN 1 ELSE @INTERVAL END, 0);
    ELSE IF EXISTS (
        SELECT 1 FROM dbo.RETENTION_CARD WHERE CARDID = @CARDID AND MASTERYSTATE = N'LEARNING'
    )
        UPDATE dbo.RETENTION_SCHEDULE
        SET DUEAT = CASE WHEN DUEAT > @DUE THEN @DUE ELSE DUEAT END,
            INTERVALDAYS = CASE WHEN @INTERVAL < 1 THEN 1 ELSE @INTERVAL END,
            UPDATEDDATE = SYSUTCDATETIME()
        WHERE CARDID = @CARDID;

    -- Materialize today queue if due today or overdue
    IF @DUE <= CAST(SYSUTCDATETIME() AS DATE)
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM dbo.RETENTION_DAILY_QUEUE
            WHERE USERID = @USERID AND QUEUEDATE = CAST(SYSUTCDATETIME() AS DATE) AND CARDID = @CARDID
        )
            INSERT INTO dbo.RETENTION_DAILY_QUEUE (USERID, QUEUEDATE, CARDID, PRIORITY, STATUS)
            VALUES (@USERID, CAST(SYSUTCDATETIME() AS DATE), @CARDID, 50, N'DUE');
    END

    SELECT 1 AS SUCCESS, @CARDID AS CARDID, 'UPSERTED' AS ACTION, @DUE AS DUEAT;
END
GO

CREATE OR ALTER PROCEDURE dbo.USP_RETENTION_GET_TODAY
(
    @USERID INT,
    @QUEUEDATE DATE = NULL,
    @LIMIT INT = 50
)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @D DATE = ISNULL(@QUEUEDATE, CAST(SYSUTCDATETIME() AS DATE));

    -- Refresh queue from schedules
    INSERT INTO dbo.RETENTION_DAILY_QUEUE (USERID, QUEUEDATE, CARDID, PRIORITY, STATUS)
    SELECT C.USERID, @D, C.CARDID,
           CASE WHEN S.DUEAT < @D THEN 10 ELSE 40 END,
           N'DUE'
    FROM dbo.RETENTION_CARD C
    INNER JOIN dbo.RETENTION_SCHEDULE S ON S.CARDID = C.CARDID
    WHERE C.USERID = @USERID
      AND C.ISACTIVE = 1
      AND C.MASTERYSTATE <> N'MASTERED'
      AND S.DUEAT <= @D
      AND NOT EXISTS (
          SELECT 1 FROM dbo.RETENTION_DAILY_QUEUE Q
          WHERE Q.USERID = C.USERID AND Q.QUEUEDATE = @D AND Q.CARDID = C.CARDID
      );

    SELECT TOP (@LIMIT)
        C.CARDID,
        C.SOURCETYPE,
        C.SOURCEID,
        C.ENROLLMENTID,
        C.PLANID,
        C.SLOTID,
        C.TOPICID,
        C.TITLE,
        C.SLOTTYPE,
        C.REVIEWMETHOD,
        C.REVIEWDIFFICULTY,
        C.REVIEWTEMPLATE,
        C.ESTIMATEDRECALLMINUTES,
        C.MASTERYSTATE,
        S.DUEAT,
        S.INTERVALDAYS,
        S.REPETITION,
        S.EASEFACTOR,
        CASE WHEN S.DUEAT < @D THEN 1 ELSE 0 END AS ISOVERDUE,
        DATEDIFF(DAY, S.DUEAT, @D) AS DAYSOVERDUE
    FROM dbo.RETENTION_CARD C
    INNER JOIN dbo.RETENTION_SCHEDULE S ON S.CARDID = C.CARDID
    WHERE C.USERID = @USERID
      AND C.ISACTIVE = 1
      AND C.MASTERYSTATE <> N'MASTERED'
      AND S.DUEAT <= @D
    ORDER BY
        CASE WHEN S.DUEAT < @D THEN 0 ELSE 1 END,
        S.DUEAT ASC,
        C.CARDID ASC;
END
GO

CREATE OR ALTER PROCEDURE dbo.USP_RETENTION_COMPLETE_ATTEMPT
(
    @USERID INT,
    @CARDID BIGINT,
    @OUTCOME NVARCHAR(32),
    @CONFIDENCE TINYINT = NULL,
    @DURATIONSECONDS INT = NULL,
    @TEMPLATEUSED NVARCHAR(32) = NULL,
    @RESPONSEJSON NVARCHAR(MAX) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @OWNER INT;
    DECLARE @METHOD NVARCHAR(32);
    DECLARE @MASTERY NVARCHAR(32);
    DECLARE @REP INT;
    DECLARE @INTERVAL INT;
    DECLARE @EASE DECIMAL(6,3);

    SELECT @OWNER = C.USERID, @METHOD = C.REVIEWMETHOD, @MASTERY = C.MASTERYSTATE
    FROM dbo.RETENTION_CARD C WHERE C.CARDID = @CARDID;

    IF @OWNER IS NULL OR @OWNER <> @USERID
    BEGIN
        SELECT 0 AS SUCCESS, 'UNAUTHORIZED' AS MESSAGE;
        RETURN;
    END

    SELECT @REP = REPETITION, @INTERVAL = INTERVALDAYS, @EASE = EASEFACTOR
    FROM dbo.RETENTION_SCHEDULE WHERE CARDID = @CARDID;

    SET @REP = ISNULL(@REP, 0);
    SET @INTERVAL = ISNULL(@INTERVAL, 1);
    SET @EASE = ISNULL(@EASE, 2.5);

    DECLARE @OUT NVARCHAR(32) = UPPER(@OUTCOME);
    DECLARE @NEWINTERVAL INT;
    DECLARE @NEWEASE DECIMAL(6,3) = @EASE;
    DECLARE @NEWREP INT = @REP;
    DECLARE @NEWMASTERY NVARCHAR(32) = @MASTERY;

    IF @OUT IN (N'AGAIN', N'FAIL')
    BEGIN
        SET @NEWINTERVAL = 1;
        SET @NEWREP = 0;
        SET @NEWEASE = CASE WHEN @EASE - 0.2 < 1.3 THEN 1.3 ELSE @EASE - 0.2 END;
        SET @NEWMASTERY = N'LEARNING';
    END
    ELSE IF @OUT = N'HARD'
    BEGIN
        SET @NEWINTERVAL = CASE WHEN @INTERVAL < 1 THEN 1 ELSE CAST(CEILING(@INTERVAL * 1.2) AS INT) END;
        SET @NEWREP = @REP + 1;
        SET @NEWEASE = CASE WHEN @EASE - 0.15 < 1.3 THEN 1.3 ELSE @EASE - 0.15 END;
    END
    ELSE IF @OUT = N'EASY'
    BEGIN
        SET @NEWINTERVAL = CASE WHEN @REP = 0 THEN 3 WHEN @REP = 1 THEN 7 ELSE CAST(CEILING(@INTERVAL * (@EASE + 0.15)) AS INT) END;
        SET @NEWREP = @REP + 1;
        SET @NEWEASE = @EASE + 0.15;
    END
    ELSE -- GOOD / COMPLETED
    BEGIN
        SET @NEWINTERVAL = CASE
            WHEN @REP = 0 THEN 1
            WHEN @REP = 1 THEN 3
            WHEN @REP = 2 THEN 7
            WHEN @REP = 3 THEN 14
            WHEN @REP = 4 THEN 30
            ELSE CAST(CEILING(@INTERVAL * @EASE) AS INT)
        END;
        SET @NEWREP = @REP + 1;
    END

    SET @NEWMASTERY = CASE
        WHEN @NEWREP <= 0 THEN N'LEARNING'
        WHEN @NEWREP = 1 THEN N'REVIEW_1'
        WHEN @NEWREP = 2 THEN N'REVIEW_2'
        WHEN @NEWREP = 3 THEN N'REVIEW_3'
        WHEN @NEWREP >= 5 AND @NEWINTERVAL >= 30 THEN N'MASTERED'
        ELSE N'STRONG'
    END;

    INSERT INTO dbo.RETENTION_ATTEMPT
        (CARDID, USERID, OUTCOME, CONFIDENCE, DURATIONSECONDS, TEMPLATEUSED, RESPONSEJSON)
    VALUES
        (@CARDID, @USERID, @OUT, @CONFIDENCE, @DURATIONSECONDS, @TEMPLATEUSED, @RESPONSEJSON);

    DECLARE @NEXT DATE = DATEADD(DAY, @NEWINTERVAL, CAST(SYSUTCDATETIME() AS DATE));

    UPDATE dbo.RETENTION_SCHEDULE
    SET DUEAT = @NEXT,
        INTERVALDAYS = @NEWINTERVAL,
        REPETITION = @NEWREP,
        EASEFACTOR = @NEWEASE,
        LASTREVIEWEDAT = SYSUTCDATETIME(),
        UPDATEDDATE = SYSUTCDATETIME()
    WHERE CARDID = @CARDID;

    UPDATE dbo.RETENTION_CARD
    SET MASTERYSTATE = @NEWMASTERY,
        UPDATEDDATE = SYSUTCDATETIME()
    WHERE CARDID = @CARDID;

    UPDATE dbo.RETENTION_DAILY_QUEUE
    SET STATUS = N'DONE'
    WHERE USERID = @USERID
      AND QUEUEDATE = CAST(SYSUTCDATETIME() AS DATE)
      AND CARDID = @CARDID;

    SELECT 1 AS SUCCESS,
           @CARDID AS CARDID,
           @NEWMASTERY AS MASTERYSTATE,
           @NEXT AS NEXTREVIEWDATE,
           @NEWINTERVAL AS INTERVALDAYS,
           @NEWREP AS REPETITION;
END
GO

CREATE OR ALTER PROCEDURE dbo.USP_RETENTION_GET_CARDS
(
    @USERID INT,
    @ENROLLMENTID BIGINT = NULL,
    @LIMIT INT = 100
)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP (@LIMIT)
        C.CARDID, C.SOURCETYPE, C.SOURCEID, C.ENROLLMENTID, C.PLANID, C.SLOTID, C.TOPICID,
        C.TITLE, C.SLOTTYPE, C.REVIEWMETHOD, C.REVIEWDIFFICULTY, C.REVIEWTEMPLATE,
        C.ESTIMATEDRECALLMINUTES, C.REVIEWCONFIGJSON, C.MASTERYSTATE, C.ISACTIVE,
        S.DUEAT, S.INTERVALDAYS, S.REPETITION, S.EASEFACTOR, S.LASTREVIEWEDAT
    FROM dbo.RETENTION_CARD C
    LEFT JOIN dbo.RETENTION_SCHEDULE S ON S.CARDID = C.CARDID
    WHERE C.USERID = @USERID
      AND (@ENROLLMENTID IS NULL OR C.ENROLLMENTID = @ENROLLMENTID)
    ORDER BY
        CASE C.MASTERYSTATE WHEN N'MASTERED' THEN 2 ELSE 0 END,
        S.DUEAT ASC;
END
GO

CREATE OR ALTER PROCEDURE dbo.USP_RETENTION_MASTERY_SUMMARY
(
    @USERID INT,
    @ENROLLMENTID BIGINT = NULL
)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT
        COUNT(*) AS TotalCards,
        SUM(CASE WHEN MASTERYSTATE = N'MASTERED' THEN 1 ELSE 0 END) AS MasteredCards,
        SUM(CASE WHEN MASTERYSTATE = N'LEARNING' THEN 1 ELSE 0 END) AS LearningCards,
        SUM(CASE WHEN MASTERYSTATE LIKE N'REVIEW_%' THEN 1 ELSE 0 END) AS InReviewCards,
        SUM(CASE WHEN MASTERYSTATE = N'STRONG' THEN 1 ELSE 0 END) AS StrongCards,
        CASE WHEN COUNT(*) = 0 THEN 0
             ELSE CAST(100.0 * SUM(CASE WHEN MASTERYSTATE = N'MASTERED' THEN 1 ELSE 0 END) / COUNT(*) AS DECIMAL(5,1))
        END AS MasteryPercent
    FROM dbo.RETENTION_CARD
    WHERE USERID = @USERID
      AND ISACTIVE = 1
      AND (@ENROLLMENTID IS NULL OR ENROLLMENTID = @ENROLLMENTID);
END
GO

CREATE OR ALTER PROCEDURE dbo.USP_RETENTION_UPSERT_GUIDED_TOPIC
(
    @USERID INT,
    @TOPICID INT,
    @TITLE NVARCHAR(300) = NULL,
    @LEITNERBOX INT = 1,
    @NEXTREVIEWDATE DATE = NULL,
    @MASTERYLEVEL NVARCHAR(32) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @SOURCEID NVARCHAR(64) = CONCAT(N'topic:', CAST(@TOPICID AS NVARCHAR(32)));
    DECLARE @CARDID BIGINT;
    DECLARE @MASTERY NVARCHAR(32) = CASE UPPER(ISNULL(@MASTERYLEVEL, N''))
        WHEN N'MASTERED' THEN N'MASTERED'
        WHEN N'PROFICIENT' THEN N'STRONG'
        WHEN N'FAMILIAR' THEN N'REVIEW_2'
        WHEN N'BEGINNER' THEN N'REVIEW_1'
        ELSE N'LEARNING'
    END;
    DECLARE @INTERVAL INT = CASE ISNULL(@LEITNERBOX, 1)
        WHEN 1 THEN 1 WHEN 2 THEN 3 WHEN 3 THEN 7 WHEN 4 THEN 14 ELSE 1 END;
    DECLARE @DUE DATE = ISNULL(@NEXTREVIEWDATE, DATEADD(DAY, @INTERVAL, CAST(SYSUTCDATETIME() AS DATE)));

    MERGE dbo.RETENTION_CARD AS T
    USING (SELECT @USERID AS USERID, N'GUIDED_TOPIC' AS SOURCETYPE, @SOURCEID AS SOURCEID) AS S
    ON T.USERID = S.USERID AND T.SOURCETYPE = S.SOURCETYPE AND T.SOURCEID = S.SOURCEID
    WHEN MATCHED THEN UPDATE SET
        TOPICID = @TOPICID,
        TITLE = COALESCE(@TITLE, T.TITLE),
        REVIEWMETHOD = N'SPACED',
        MASTERYSTATE = @MASTERY,
        ISACTIVE = CASE WHEN @MASTERY = N'MASTERED' THEN T.ISACTIVE ELSE 1 END,
        UPDATEDDATE = SYSUTCDATETIME()
    WHEN NOT MATCHED THEN INSERT
        (USERID, SOURCETYPE, SOURCEID, TOPICID, TITLE, REVIEWMETHOD, MASTERYSTATE, ISACTIVE)
        VALUES (@USERID, N'GUIDED_TOPIC', @SOURCEID, @TOPICID, @TITLE, N'SPACED', @MASTERY, 1);

    SELECT @CARDID = CARDID FROM dbo.RETENTION_CARD
    WHERE USERID = @USERID AND SOURCETYPE = N'GUIDED_TOPIC' AND SOURCEID = @SOURCEID;

    IF NOT EXISTS (SELECT 1 FROM dbo.RETENTION_SCHEDULE WHERE CARDID = @CARDID)
        INSERT INTO dbo.RETENTION_SCHEDULE (CARDID, DUEAT, INTERVALDAYS, REPETITION)
        VALUES (@CARDID, @DUE, @INTERVAL, ISNULL(@LEITNERBOX, 1) - 1);
    ELSE
        UPDATE dbo.RETENTION_SCHEDULE
        SET DUEAT = @DUE, INTERVALDAYS = @INTERVAL, UPDATEDDATE = SYSUTCDATETIME()
        WHERE CARDID = @CARDID;

    SELECT 1 AS SUCCESS, @CARDID AS CARDID;
END
GO
