-- Phase 3: retention history + calendar (REVIEW_SERVICE)
USE [REVIEW_SERVICE]
GO

CREATE OR ALTER PROCEDURE dbo.USP_RETENTION_GET_HISTORY
(
    @USERID INT,
    @ENROLLMENTID BIGINT = NULL,
    @LIMIT INT = 50
)
AS
BEGIN
    SET NOCOUNT ON;
    SET @LIMIT = CASE WHEN @LIMIT IS NULL OR @LIMIT < 1 THEN 50
                      WHEN @LIMIT > 200 THEN 200 ELSE @LIMIT END;

    SELECT TOP (@LIMIT)
        A.ATTEMPTID,
        A.CARDID,
        A.OUTCOME,
        A.CONFIDENCE,
        A.DURATIONSECONDS,
        A.TEMPLATEUSED,
        A.ATTEMPTEDAT,
        C.TITLE,
        C.MASTERYSTATE,
        C.ENROLLMENTID,
        C.SOURCETYPE,
        C.REVIEWTEMPLATE
    FROM dbo.RETENTION_ATTEMPT A
    INNER JOIN dbo.RETENTION_CARD C ON C.CARDID = A.CARDID
    WHERE A.USERID = @USERID
      AND (@ENROLLMENTID IS NULL OR C.ENROLLMENTID = @ENROLLMENTID)
    ORDER BY A.ATTEMPTEDAT DESC;
END
GO

CREATE OR ALTER PROCEDURE dbo.USP_RETENTION_GET_CALENDAR
(
    @USERID INT,
    @FROMDATE DATE,
    @TODATE DATE
)
AS
BEGIN
    SET NOCOUNT ON;

    IF @FROMDATE IS NULL SET @FROMDATE = DATEADD(DAY, -14, CAST(SYSUTCDATETIME() AS DATE));
    IF @TODATE IS NULL SET @TODATE = DATEADD(DAY, 30, CAST(SYSUTCDATETIME() AS DATE));

    -- Due schedule days
    SELECT
        S.DUEAT AS CALENDARDATE,
        N'DUE' AS KIND,
        COUNT(*) AS CARDCOUNT
    FROM dbo.RETENTION_SCHEDULE S
    INNER JOIN dbo.RETENTION_CARD C ON C.CARDID = S.CARDID
    WHERE C.USERID = @USERID
      AND C.ISACTIVE = 1
      AND C.MASTERYSTATE <> N'MASTERED'
      AND S.DUEAT >= @FROMDATE
      AND S.DUEAT <= @TODATE
    GROUP BY S.DUEAT

    UNION ALL

    -- Completed attempt days
    SELECT
        CAST(A.ATTEMPTEDAT AS DATE) AS CALENDARDATE,
        N'COMPLETED' AS KIND,
        COUNT(*) AS CARDCOUNT
    FROM dbo.RETENTION_ATTEMPT A
    WHERE A.USERID = @USERID
      AND CAST(A.ATTEMPTEDAT AS DATE) >= @FROMDATE
      AND CAST(A.ATTEMPTEDAT AS DATE) <= @TODATE
    GROUP BY CAST(A.ATTEMPTEDAT AS DATE)
    ORDER BY CALENDARDATE ASC, KIND ASC;
END
GO
